# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ai2thor.api import image_pb2 as ai2thor_dot_api_dot_image__pb2


class ImageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetImage = channel.unary_unary(
                '/ai2thor.api.ImageService/GetImage',
                request_serializer=ai2thor_dot_api_dot_image__pb2.ImageRequest.SerializeToString,
                response_deserializer=ai2thor_dot_api_dot_image__pb2.Image.FromString,
                )
        self.GetAllImages = channel.unary_unary(
                '/ai2thor.api.ImageService/GetAllImages',
                request_serializer=ai2thor_dot_api_dot_image__pb2.ImageRequest.SerializeToString,
                response_deserializer=ai2thor_dot_api_dot_image__pb2.GetImageResponses.FromString,
                )


class ImageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetImage(self, request, context):
        """Reqeust an image by name, with optional parameters for request image size or quality level
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=ai2thor_dot_api_dot_image__pb2.ImageRequest.FromString,
                    response_serializer=ai2thor_dot_api_dot_image__pb2.Image.SerializeToString,
            ),
            'GetAllImages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllImages,
                    request_deserializer=ai2thor_dot_api_dot_image__pb2.ImageRequest.FromString,
                    response_serializer=ai2thor_dot_api_dot_image__pb2.GetImageResponses.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai2thor.api.ImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai2thor.api.ImageService/GetImage',
            ai2thor_dot_api_dot_image__pb2.ImageRequest.SerializeToString,
            ai2thor_dot_api_dot_image__pb2.Image.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai2thor.api.ImageService/GetAllImages',
            ai2thor_dot_api_dot_image__pb2.ImageRequest.SerializeToString,
            ai2thor_dot_api_dot_image__pb2.GetImageResponses.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
