# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai2thor/api/robot_command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ai2thor/api/robot_command.proto',
  package='ai2thor.api',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1f\x61i2thor/api/robot_command.proto\x12\x0b\x61i2thor.api\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n\x13RobotCommandRequest\x12\x31\n\x0erobot_commands\x18\x01 \x03(\x0b\x32\x19.ai2thor.api.RobotCommand\"~\n\x0cRobotCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x31\n\x04\x61rgs\x18\x02 \x03(\x0b\x32#.ai2thor.api.RobotCommand.ArgsEntry\x1a+\n\tArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\xcc\x01\n\x14RobotCommandResponse\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x43\n\x0c\x65rror_status\x18\x03 \x01(\x0e\x32-.ai2thor.api.RobotCommandResponse.ErrorStatus\"/\n\x0b\x45rrorStatus\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x12\n\x0eUNKNOWN_ACTION\x10\x01\x32i\n\x13RobotCommandService\x12R\n\tMoveRobot\x12 .ai2thor.api.RobotCommandRequest\x1a!.ai2thor.api.RobotCommandResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_ROBOTCOMMANDRESPONSE_ERRORSTATUS = _descriptor.EnumDescriptor(
  name='ErrorStatus',
  full_name='ai2thor.api.RobotCommandResponse.ErrorStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ACTION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=441,
  serialized_end=488,
)
_sym_db.RegisterEnumDescriptor(_ROBOTCOMMANDRESPONSE_ERRORSTATUS)


_ROBOTCOMMANDREQUEST = _descriptor.Descriptor(
  name='RobotCommandRequest',
  full_name='ai2thor.api.RobotCommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_commands', full_name='ai2thor.api.RobotCommandRequest.robot_commands', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=153,
)


_ROBOTCOMMAND_ARGSENTRY = _descriptor.Descriptor(
  name='ArgsEntry',
  full_name='ai2thor.api.RobotCommand.ArgsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ai2thor.api.RobotCommand.ArgsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ai2thor.api.RobotCommand.ArgsEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=281,
)

_ROBOTCOMMAND = _descriptor.Descriptor(
  name='RobotCommand',
  full_name='ai2thor.api.RobotCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='ai2thor.api.RobotCommand.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='ai2thor.api.RobotCommand.args', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ROBOTCOMMAND_ARGSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=281,
)


_ROBOTCOMMANDRESPONSE = _descriptor.Descriptor(
  name='RobotCommandResponse',
  full_name='ai2thor.api.RobotCommandResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ai2thor.api.RobotCommandResponse.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='ai2thor.api.RobotCommandResponse.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_status', full_name='ai2thor.api.RobotCommandResponse.error_status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ROBOTCOMMANDRESPONSE_ERRORSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=488,
)

_ROBOTCOMMANDREQUEST.fields_by_name['robot_commands'].message_type = _ROBOTCOMMAND
_ROBOTCOMMAND_ARGSENTRY.containing_type = _ROBOTCOMMAND
_ROBOTCOMMAND.fields_by_name['args'].message_type = _ROBOTCOMMAND_ARGSENTRY
_ROBOTCOMMANDRESPONSE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ROBOTCOMMANDRESPONSE.fields_by_name['error_status'].enum_type = _ROBOTCOMMANDRESPONSE_ERRORSTATUS
_ROBOTCOMMANDRESPONSE_ERRORSTATUS.containing_type = _ROBOTCOMMANDRESPONSE
DESCRIPTOR.message_types_by_name['RobotCommandRequest'] = _ROBOTCOMMANDREQUEST
DESCRIPTOR.message_types_by_name['RobotCommand'] = _ROBOTCOMMAND
DESCRIPTOR.message_types_by_name['RobotCommandResponse'] = _ROBOTCOMMANDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotCommandRequest = _reflection.GeneratedProtocolMessageType('RobotCommandRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTCOMMANDREQUEST,
  '__module__' : 'ai2thor.api.robot_command_pb2'
  # @@protoc_insertion_point(class_scope:ai2thor.api.RobotCommandRequest)
  })
_sym_db.RegisterMessage(RobotCommandRequest)

RobotCommand = _reflection.GeneratedProtocolMessageType('RobotCommand', (_message.Message,), {

  'ArgsEntry' : _reflection.GeneratedProtocolMessageType('ArgsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ROBOTCOMMAND_ARGSENTRY,
    '__module__' : 'ai2thor.api.robot_command_pb2'
    # @@protoc_insertion_point(class_scope:ai2thor.api.RobotCommand.ArgsEntry)
    })
  ,
  'DESCRIPTOR' : _ROBOTCOMMAND,
  '__module__' : 'ai2thor.api.robot_command_pb2'
  # @@protoc_insertion_point(class_scope:ai2thor.api.RobotCommand)
  })
_sym_db.RegisterMessage(RobotCommand)
_sym_db.RegisterMessage(RobotCommand.ArgsEntry)

RobotCommandResponse = _reflection.GeneratedProtocolMessageType('RobotCommandResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTCOMMANDRESPONSE,
  '__module__' : 'ai2thor.api.robot_command_pb2'
  # @@protoc_insertion_point(class_scope:ai2thor.api.RobotCommandResponse)
  })
_sym_db.RegisterMessage(RobotCommandResponse)


_ROBOTCOMMAND_ARGSENTRY._options = None

_ROBOTCOMMANDSERVICE = _descriptor.ServiceDescriptor(
  name='RobotCommandService',
  full_name='ai2thor.api.RobotCommandService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=490,
  serialized_end=595,
  methods=[
  _descriptor.MethodDescriptor(
    name='MoveRobot',
    full_name='ai2thor.api.RobotCommandService.MoveRobot',
    index=0,
    containing_service=None,
    input_type=_ROBOTCOMMANDREQUEST,
    output_type=_ROBOTCOMMANDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROBOTCOMMANDSERVICE)

DESCRIPTOR.services_by_name['RobotCommandService'] = _ROBOTCOMMANDSERVICE

# @@protoc_insertion_point(module_scope)
