# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ai2thor.api import robot_state_pb2 as ai2thor_dot_api_dot_robot__state__pb2


class RobotStateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRobotState = channel.unary_unary(
                '/ai2thor.api.RobotStateService/GetRobotState',
                request_serializer=ai2thor_dot_api_dot_robot__state__pb2.RobotStateRequest.SerializeToString,
                response_deserializer=ai2thor_dot_api_dot_robot__state__pb2.RobotState.FromString,
                )


class RobotStateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRobotState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotStateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRobotState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotState,
                    request_deserializer=ai2thor_dot_api_dot_robot__state__pb2.RobotStateRequest.FromString,
                    response_serializer=ai2thor_dot_api_dot_robot__state__pb2.RobotState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai2thor.api.RobotStateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RobotStateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRobotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai2thor.api.RobotStateService/GetRobotState',
            ai2thor_dot_api_dot_robot__state__pb2.RobotStateRequest.SerializeToString,
            ai2thor_dot_api_dot_robot__state__pb2.RobotState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
