# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ai2thor.api import robot_command_pb2 as ai2thor_dot_api_dot_robot__command__pb2


class RobotCommandServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MoveRobot = channel.unary_unary(
                '/ai2thor.api.RobotCommandService/MoveRobot',
                request_serializer=ai2thor_dot_api_dot_robot__command__pb2.RobotCommandRequest.SerializeToString,
                response_deserializer=ai2thor_dot_api_dot_robot__command__pb2.RobotCommandResponse.FromString,
                )


class RobotCommandServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MoveRobot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotCommandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MoveRobot': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveRobot,
                    request_deserializer=ai2thor_dot_api_dot_robot__command__pb2.RobotCommandRequest.FromString,
                    response_serializer=ai2thor_dot_api_dot_robot__command__pb2.RobotCommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai2thor.api.RobotCommandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RobotCommandService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MoveRobot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai2thor.api.RobotCommandService/MoveRobot',
            ai2thor_dot_api_dot_robot__command__pb2.RobotCommandRequest.SerializeToString,
            ai2thor_dot_api_dot_robot__command__pb2.RobotCommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
