using UnityEngine;
// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class DroneAgentMetadataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::DroneAgentMetadata>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public DroneAgentMetadataFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "LauncherPosition", 0 },
                { "name", 1 },
                { "position", 2 },
                { "rotation", 3 },
                { "cameraHorizon", 4 },
                { "isStanding", 5 },
                { "inHighFrictionArea", 6 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("LauncherPosition"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("name"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("position"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("rotation"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("cameraHorizon"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("isStanding"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("inHighFrictionArea"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::DroneAgentMetadata value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(7);
            writer.WriteRaw(this.____stringByteKeys[0]);
            formatterResolver.GetFormatterWithVerify<Vector3>().Serialize(ref writer, value.LauncherPosition, options);
            writer.WriteRaw(this.____stringByteKeys[1]);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.name, options);
            writer.WriteRaw(this.____stringByteKeys[2]);
            formatterResolver.GetFormatterWithVerify<Vector3>().Serialize(ref writer, value.position, options);
            writer.WriteRaw(this.____stringByteKeys[3]);
            formatterResolver.GetFormatterWithVerify<Vector3>().Serialize(ref writer, value.rotation, options);
            writer.WriteRaw(this.____stringByteKeys[4]);
            writer.Write(value.cameraHorizon);
            writer.WriteRaw(this.____stringByteKeys[5]);
            formatterResolver.GetFormatterWithVerify<bool?>().Serialize(ref writer, value.isStanding, options);
            writer.WriteRaw(this.____stringByteKeys[6]);
            writer.Write(value.inHighFrictionArea);
        }

        public global::DroneAgentMetadata Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __LauncherPosition__ = default(Vector3);
            var __name__ = default(string);
            var __position__ = default(Vector3);
            var __rotation__ = default(Vector3);
            var __cameraHorizon__ = default(float);
            var __isStanding__ = default(bool?);
            var __inHighFrictionArea__ = default(bool);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySpan<byte> stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __LauncherPosition__ = formatterResolver.GetFormatterWithVerify<Vector3>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __name__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __position__ = formatterResolver.GetFormatterWithVerify<Vector3>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __rotation__ = formatterResolver.GetFormatterWithVerify<Vector3>().Deserialize(ref reader, options);
                        break;
                    case 4:
                        __cameraHorizon__ = reader.ReadSingle();
                        break;
                    case 5:
                        __isStanding__ = formatterResolver.GetFormatterWithVerify<bool?>().Deserialize(ref reader, options);
                        break;
                    case 6:
                        __inHighFrictionArea__ = reader.ReadBoolean();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::DroneAgentMetadata();
            ____result.LauncherPosition = __LauncherPosition__;
            ____result.name = __name__;
            ____result.position = __position__;
            ____result.rotation = __rotation__;
            ____result.cameraHorizon = __cameraHorizon__;
            ____result.isStanding = __isStanding__;
            ____result.inHighFrictionArea = __inHighFrictionArea__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
