using UnityEngine;
// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class ArmMetadataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::ArmMetadata>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public ArmMetadataFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "joints", 0 },
                { "heldObjects", 1 },
                { "pickupableObjects", 2 },
                { "handSphereCenter", 3 },
                { "handSphereRadius", 4 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("joints"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("heldObjects"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("pickupableObjects"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("handSphereCenter"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("handSphereRadius"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::ArmMetadata value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(5);
            writer.WriteRaw(this.____stringByteKeys[0]);
            formatterResolver.GetFormatterWithVerify<global::JointMetadata[]>().Serialize(ref writer, value.joints, options);
            writer.WriteRaw(this.____stringByteKeys[1]);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<string>>().Serialize(ref writer, value.heldObjects, options);
            writer.WriteRaw(this.____stringByteKeys[2]);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<string>>().Serialize(ref writer, value.pickupableObjects, options);
            writer.WriteRaw(this.____stringByteKeys[3]);
            formatterResolver.GetFormatterWithVerify<Vector3>().Serialize(ref writer, value.handSphereCenter, options);
            writer.WriteRaw(this.____stringByteKeys[4]);
            writer.Write(value.handSphereRadius);
        }

        public global::ArmMetadata Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __joints__ = default(global::JointMetadata[]);
            var __heldObjects__ = default(global::System.Collections.Generic.List<string>);
            var __pickupableObjects__ = default(global::System.Collections.Generic.List<string>);
            var __handSphereCenter__ = default(Vector3);
            var __handSphereRadius__ = default(float);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySpan<byte> stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __joints__ = formatterResolver.GetFormatterWithVerify<global::JointMetadata[]>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __heldObjects__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<string>>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __pickupableObjects__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<string>>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __handSphereCenter__ = formatterResolver.GetFormatterWithVerify<Vector3>().Deserialize(ref reader, options);
                        break;
                    case 4:
                        __handSphereRadius__ = reader.ReadSingle();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::ArmMetadata();
            ____result.joints = __joints__;
            ____result.heldObjects = __heldObjects__;
            ____result.pickupableObjects = __pickupableObjects__;
            ____result.handSphereCenter = __handSphereCenter__;
            ____result.handSphereRadius = __handSphereRadius__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
