using UnityEngine;
// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class MetadataPatchFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::MetadataPatch>
    {
        global::MessagePack.Formatters.ActionReturnFormatter __actionReturnCustomFormatter__ = new global::MessagePack.Formatters.ActionReturnFormatter();


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public MetadataPatchFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "lastAction", 0 },
                { "errorMessage", 1 },
                { "errorCode", 2 },
                { "lastActionSuccess", 3 },
                { "agentId", 4 },
                { "actionReturn", 5 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("lastAction"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("errorMessage"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("errorCode"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("lastActionSuccess"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("agentId"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("actionReturn"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::MetadataPatch value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(6);
            writer.WriteRaw(this.____stringByteKeys[0]);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.lastAction, options);
            writer.WriteRaw(this.____stringByteKeys[1]);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.errorMessage, options);
            writer.WriteRaw(this.____stringByteKeys[2]);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.errorCode, options);
            writer.WriteRaw(this.____stringByteKeys[3]);
            writer.Write(value.lastActionSuccess);
            writer.WriteRaw(this.____stringByteKeys[4]);
            writer.Write(value.agentId);
            writer.WriteRaw(this.____stringByteKeys[5]);
            this.__actionReturnCustomFormatter__.Serialize(ref writer, value.actionReturn, options);
        }

        public global::MetadataPatch Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __lastAction__ = default(string);
            var __errorMessage__ = default(string);
            var __errorCode__ = default(string);
            var __lastActionSuccess__ = default(bool);
            var __agentId__ = default(int);
            var __actionReturn__ = default(object);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySpan<byte> stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __lastAction__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __errorMessage__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __errorCode__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __lastActionSuccess__ = reader.ReadBoolean();
                        break;
                    case 4:
                        __agentId__ = reader.ReadInt32();
                        break;
                    case 5:
                        __actionReturn__ = this.__actionReturnCustomFormatter__.Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::MetadataPatch();
            ____result.lastAction = __lastAction__;
            ____result.errorMessage = __errorMessage__;
            ____result.errorCode = __errorCode__;
            ____result.lastActionSuccess = __lastActionSuccess__;
            ____result.agentId = __agentId__;
            ____result.actionReturn = __actionReturn__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
