using UnityEngine;
// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class JointMetadataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::JointMetadata>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public JointMetadataFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "name", 0 },
                { "position", 1 },
                { "rootRelativePosition", 2 },
                { "rotation", 3 },
                { "rootRelativeRotation", 4 },
                { "localRotation", 5 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("name"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("position"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("rootRelativePosition"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("rotation"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("rootRelativeRotation"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("localRotation"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::JointMetadata value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(6);
            writer.WriteRaw(this.____stringByteKeys[0]);
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.name, options);
            writer.WriteRaw(this.____stringByteKeys[1]);
            formatterResolver.GetFormatterWithVerify<Vector3>().Serialize(ref writer, value.position, options);
            writer.WriteRaw(this.____stringByteKeys[2]);
            formatterResolver.GetFormatterWithVerify<Vector3>().Serialize(ref writer, value.rootRelativePosition, options);
            writer.WriteRaw(this.____stringByteKeys[3]);
            formatterResolver.GetFormatterWithVerify<Vector4>().Serialize(ref writer, value.rotation, options);
            writer.WriteRaw(this.____stringByteKeys[4]);
            formatterResolver.GetFormatterWithVerify<Vector4>().Serialize(ref writer, value.rootRelativeRotation, options);
            writer.WriteRaw(this.____stringByteKeys[5]);
            formatterResolver.GetFormatterWithVerify<Vector4>().Serialize(ref writer, value.localRotation, options);
        }

        public global::JointMetadata Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __name__ = default(string);
            var __position__ = default(Vector3);
            var __rootRelativePosition__ = default(Vector3);
            var __rotation__ = default(Vector4);
            var __rootRelativeRotation__ = default(Vector4);
            var __localRotation__ = default(Vector4);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySpan<byte> stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __name__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __position__ = formatterResolver.GetFormatterWithVerify<Vector3>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __rootRelativePosition__ = formatterResolver.GetFormatterWithVerify<Vector3>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __rotation__ = formatterResolver.GetFormatterWithVerify<Vector4>().Deserialize(ref reader, options);
                        break;
                    case 4:
                        __rootRelativeRotation__ = formatterResolver.GetFormatterWithVerify<Vector4>().Deserialize(ref reader, options);
                        break;
                    case 5:
                        __localRotation__ = formatterResolver.GetFormatterWithVerify<Vector4>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::JointMetadata();
            ____result.name = __name__;
            ____result.position = __position__;
            ____result.rootRelativePosition = __rootRelativePosition__;
            ____result.rotation = __rotation__;
            ____result.rootRelativeRotation = __rootRelativeRotation__;
            ____result.localRotation = __localRotation__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
