using UnityEngine;
// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class ThirdPartyCameraMetadataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::ThirdPartyCameraMetadata>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public ThirdPartyCameraMetadataFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "thirdPartyCameraId", 0 },
                { "position", 1 },
                { "rotation", 2 },
                { "fieldOfView", 3 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("thirdPartyCameraId"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("position"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("rotation"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("fieldOfView"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::ThirdPartyCameraMetadata value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(4);
            writer.WriteRaw(this.____stringByteKeys[0]);
            writer.Write(value.thirdPartyCameraId);
            writer.WriteRaw(this.____stringByteKeys[1]);
            formatterResolver.GetFormatterWithVerify<Vector3>().Serialize(ref writer, value.position, options);
            writer.WriteRaw(this.____stringByteKeys[2]);
            formatterResolver.GetFormatterWithVerify<Vector3>().Serialize(ref writer, value.rotation, options);
            writer.WriteRaw(this.____stringByteKeys[3]);
            writer.Write(value.fieldOfView);
        }

        public global::ThirdPartyCameraMetadata Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __thirdPartyCameraId__ = default(int);
            var __position__ = default(Vector3);
            var __rotation__ = default(Vector3);
            var __fieldOfView__ = default(float);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySpan<byte> stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __thirdPartyCameraId__ = reader.ReadInt32();
                        break;
                    case 1:
                        __position__ = formatterResolver.GetFormatterWithVerify<Vector3>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __rotation__ = formatterResolver.GetFormatterWithVerify<Vector3>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __fieldOfView__ = reader.ReadSingle();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::ThirdPartyCameraMetadata();
            ____result.thirdPartyCameraId = __thirdPartyCameraId__;
            ____result.position = __position__;
            ____result.rotation = __rotation__;
            ____result.fieldOfView = __fieldOfView__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
